export default {
  login: "yhya38",
  id: 56390502,
  node_id: "MDQ6VXNlcjU2MzkwNTAy",
  avatar_url: "https://avatars0.githubusercontent.com/u/56390502?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/yhya38",
  html_url: "https://github.com/yhya38",
  followers_url: "https://api.github.com/users/yhya38/followers",
  following_url: "https://api.github.com/users/yhya38/following{/other_user}",
  gists_url: "https://api.github.com/users/yhya38/gists{/gist_id}",
  starred_url: "https://api.github.com/users/yhya38/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/yhya38/subscriptions",
  organizations_url: "https://api.github.com/users/yhya38/orgs",
  repos_url: "https://api.github.com/users/yhya38/repos",
  events_url: "https://api.github.com/users/yhya38/events{/privacy}",
  received_events_url: "https://api.github.com/users/yhya38/received_events",
  type: "User",
  site_admin: false,
  name: "yahiyakhan38",
  company: null,
  blog: "https://ykcreations.netlify.app/",
  location: "RAMANAGARAM",
  email: null,
  hireable: null,
  bio: "Frontend Web Developer, Freelancer",
  twitter_username: null,
  public_repos: 22,
  public_gists: 0,
  followers: 3,
  following: 4,
  created_at: "2019-10-10T09:58:01Z",
  updated_at: "2020-11-22T12:17:14Z",
};
